### PR TITLE
Memory pool addition + Dockerfile

### PR DESCRIPTION
**Pull request by EthanLavi**
Things changed:
1) Updated .gitignore
2) Added Dockerfile and some documentation to the README to allow for containerized development.
3) Updated CMakeLists.txt to fix some build issues 
4) Added in MemoryPool, RemotePtr, Connection/ConnectionManager, and rmalloc from existing rome
  4.a Added tests for these things as well.

### CODE REVIEW

**Comment by amandabaran** [comment]
Looks good, but curious if there are other pieces of rome/rdma that we want to update. I am wondering if we can just somehow merge the correct branch from rome?

**Comment by EthanLavi** [comment]
I think I added my edited memorypool by accident. Thought I had took the files directly from the correct branch of rome.

**Comment by amandabaran** [comment]
> I think I added my edited memorypool by accident. Thought I had took the files directly from the correct branch of rome. Will fix quickly and reopen.

What do your edits include? If its helpful stuff we should have yours in here! :)

**Comment by EthanLavi** [comment]
I was working on QP sharing within a memory pool. So you could have, for example, 20 threads sharing 10 memory pools. The idea was once you start approaching the upper limit of number of queue pairs, you start sharing memory pools among threads.

**Comment by amandabaran** [comment]
This is definitely something we will want to explore, and perhaps include it in a future work. Agreed to leave it out for now, but something we dont want to "lose"

**Pull request closed without merging**
